export interface PracticeQuestion {
  id: string
  subject: 'math' | 'science' | 'programming'
  moduleId: string
  questionNumber: number
  question: string
  options: string[]
  answer: string
  difficulty: 'easy' | 'medium' | 'hard'
  hint: string
}

export const PRACTICE_QUESTIONS: PracticeQuestion[] = [
  // ═══════════════════════════════════════════
  //  MATH — 12 Questions
  // ═══════════════════════════════════════════
  {
    id: 'math-q1',
    subject: 'math',
    moduleId: 'algebra-1',
    questionNumber: 1,
    question: 'Solve for x:  2x + 5 = 15',
    options: ['3', '5', '7', '10'],
    answer: '5',
    difficulty: 'easy',
    hint: 'Subtract 5 from both sides first, then divide by 2.',
  },
  {
    id: 'math-q2',
    subject: 'math',
    moduleId: 'algebra-1',
    questionNumber: 2,
    question: 'What is the value of y in:  3y − 9 = 0 ?',
    options: ['0', '3', '9', '-3'],
    answer: '3',
    difficulty: 'easy',
    hint: 'Add 9 to both sides, then divide by 3.',
  },
  {
    id: 'math-q3',
    subject: 'math',
    moduleId: 'algebra-1',
    questionNumber: 3,
    question: 'Simplify the expression:  4a + 2a − a',
    options: ['5a', '6a', '4a', '7a'],
    answer: '5a',
    difficulty: 'easy',
    hint: 'Combine like terms: 4 + 2 − 1 = ?',
  },
  {
    id: 'math-q4',
    subject: 'math',
    moduleId: 'algebra-1',
    questionNumber: 4,
    question: 'If x = 4, what is the value of  3x² − 2x + 1 ?',
    options: ['41', '45', '37', '49'],
    answer: '41',
    difficulty: 'medium',
    hint: 'Substitute x = 4: 3(16) − 2(4) + 1 = 48 − 8 + 1.',
  },
  {
    id: 'math-q5',
    subject: 'math',
    moduleId: 'algebra-1',
    questionNumber: 5,
    question: 'Which of the following is an equation (not an expression)?',
    options: ['3x + 7', '5y − 2', '4z + 1 = 9', 'a² + b²'],
    answer: '4z + 1 = 9',
    difficulty: 'easy',
    hint: 'An equation always has an equals sign (=).',
  },
  {
    id: 'math-q6',
    subject: 'math',
    moduleId: 'algebra-1',
    questionNumber: 6,
    question: 'Solve for m:  5(m − 2) = 3m + 4',
    options: ['5', '7', '9', '3'],
    answer: '7',
    difficulty: 'medium',
    hint: 'Distribute first: 5m − 10 = 3m + 4. Then move variables to one side.',
  },
  {
    id: 'math-q7',
    subject: 'math',
    moduleId: 'geometry-essentials',
    questionNumber: 7,
    question: 'A right triangle has legs of 6 and 8. What is the hypotenuse?',
    options: ['9', '10', '12', '14'],
    answer: '10',
    difficulty: 'medium',
    hint: 'Use the Pythagorean theorem: c² = 6² + 8² = 36 + 64 = 100.',
  },
  {
    id: 'math-q8',
    subject: 'math',
    moduleId: 'geometry-essentials',
    questionNumber: 8,
    question: 'What is the area of a rectangle with length 12 and width 5?',
    options: ['34', '60', '17', '120'],
    answer: '60',
    difficulty: 'easy',
    hint: 'Area = length × width.',
  },
  {
    id: 'math-q9',
    subject: 'math',
    moduleId: 'quadratic-equations',
    questionNumber: 9,
    question: 'Solve x² − 9 = 0. What are the solutions?',
    options: ['x = 3 only', 'x = ±3', 'x = 9', 'x = ±9'],
    answer: 'x = ±3',
    difficulty: 'medium',
    hint: 'Factor as (x−3)(x+3) = 0, or take the square root of both sides.',
  },
  {
    id: 'math-q10',
    subject: 'math',
    moduleId: 'quadratic-equations',
    questionNumber: 10,
    question: 'What is the discriminant of  x² + 4x + 4 = 0 ?',
    options: ['0', '8', '16', '-16'],
    answer: '0',
    difficulty: 'hard',
    hint: 'Discriminant = b² − 4ac = 16 − 4(1)(4).',
  },
  {
    id: 'math-q11',
    subject: 'math',
    moduleId: 'geometry-essentials',
    questionNumber: 11,
    question: 'An angle measuring 135° is classified as:',
    options: ['Acute', 'Right', 'Obtuse', 'Straight'],
    answer: 'Obtuse',
    difficulty: 'easy',
    hint: 'Obtuse angles are between 90° and 180°.',
  },
  {
    id: 'math-q12',
    subject: 'math',
    moduleId: 'algebra-1',
    questionNumber: 12,
    question: 'Solve:  x/4 + 3 = 7',
    options: ['4', '10', '16', '28'],
    answer: '16',
    difficulty: 'medium',
    hint: 'Subtract 3 from both sides → x/4 = 4 → multiply by 4.',
  },
  {
    id: 'math-q13',
    subject: 'math',
    moduleId: 'algebra-1',
    questionNumber: 13,
    question: 'Solve for x:  3x − 4 = 11',
    options: ['3', '4', '5', '6'],
    answer: '5',
    difficulty: 'easy',
    hint: 'Add 4 to both sides, then divide by 3.',
  },
  {
    id: 'math-q14',
    subject: 'math',
    moduleId: 'algebra-1',
    questionNumber: 14,
    question: 'Find the value of x if  2(x + 3) = 14',
    options: ['4', '5', '7', '10'],
    answer: '4',
    difficulty: 'medium',
    hint: 'Divide both sides by 2 first, then subtract 3.',
  },
  {
    id: 'math-q15',
    subject: 'math',
    moduleId: 'algebra-1',
    questionNumber: 15,
    question: 'Simplify the expression:  2(3x + 4) − 5x',
    options: ['x + 8', 'x + 4', '11x + 8', 'x - 8'],
    answer: 'x + 8',
    difficulty: 'medium',
    hint: 'Distribute the 2: 6x + 8 − 5x.',
  },
  {
    id: 'math-q16',
    subject: 'math',
    moduleId: 'algebra-1',
    questionNumber: 16,
    question: 'If a = 5 and b = 2, find the value of  a² − b²',
    options: ['21', '23', '25', '29'],
    answer: '21',
    difficulty: 'easy',
    hint: 'Substitute the values: 5² − 2² = 25 − 4.',
  },
  {
    id: 'math-q17',
    subject: 'math',
    moduleId: 'algebra-1',
    questionNumber: 17,
    question: 'Solve for x:  7x + 2 = 5x + 10',
    options: ['2', '4', '6', '8'],
    answer: '4',
    difficulty: 'medium',
    hint: 'Subtract 5x from both sides, then subtract 2.',
  },
  {
    id: 'math-q18',
    subject: 'math',
    moduleId: 'algebra-1',
    questionNumber: 18,
    question: 'What is the value of x in  4x/2 = 10 ?',
    options: ['2', '5', '10', '20'],
    answer: '5',
    difficulty: 'easy',
    hint: 'Simplify 4x/2 to 2x, then solve 2x = 10.',
  },
  {
    id: 'math-q19',
    subject: 'math',
    moduleId: 'geometry-essentials',
    questionNumber: 19,
    question: 'What is the sum of the interior angles of a triangle?',
    options: ['90°', '180°', '270°', '360°'],
    answer: '180°',
    difficulty: 'easy',
    hint: 'This is a fundamental property of triangles in Euclidean geometry.',
  },
  {
    id: 'math-q20',
    subject: 'math',
    moduleId: 'algebra-1',
    questionNumber: 20,
    question: 'Solve for y:  15 − 3y = 6',
    options: ['3', '5', '7', '9'],
    answer: '3',
    difficulty: 'medium',
    hint: 'Subtract 15 from both sides, then divide by -3.',
  },

  // ═══════════════════════════════════════════
  //  SCIENCE — 20 Questions
  // ═══════════════════════════════════════════
  {
    id: 'sci-q1',
    subject: 'science',
    moduleId: 'newtons-laws',
    questionNumber: 1,
    question: 'Which law is known as the Law of Inertia?',
    options: ["Newton's First Law", "Newton's Second Law", "Newton's Third Law", 'Law of Gravitation'],
    answer: "Newton's First Law",
    difficulty: 'easy',
    hint: 'Inertia is the tendency of objects to resist changes in motion.',
  },
  {
    id: 'sci-q2',
    subject: 'science',
    moduleId: 'newtons-laws',
    questionNumber: 2,
    question: "F = ma is a statement of Newton's _____ Law.",
    options: ['First', 'Second', 'Third', 'Fourth'],
    answer: 'Second',
    difficulty: 'easy',
    hint: 'This law relates force, mass, and acceleration.',
  },
  {
    id: 'sci-q3',
    subject: 'science',
    moduleId: 'newtons-laws',
    questionNumber: 3,
    question: 'A 5 kg box is pushed with a force of 20 N. What is its acceleration?',
    options: ['2 m/s²', '4 m/s²', '10 m/s²', '100 m/s²'],
    answer: '4 m/s²',
    difficulty: 'medium',
    hint: 'Use F = ma → a = F/m = 20/5.',
  },
  {
    id: 'sci-q4',
    subject: 'science',
    moduleId: 'newtons-laws',
    questionNumber: 4,
    question: 'When you jump, the ground pushes you up. This is an example of which law?',
    options: ['First Law', 'Second Law', 'Third Law', 'None of the above'],
    answer: 'Third Law',
    difficulty: 'easy',
    hint: 'Think about action and reaction pairs.',
  },
  {
    id: 'sci-q5',
    subject: 'science',
    moduleId: 'newtons-laws',
    questionNumber: 5,
    question: 'An object moving at constant velocity has a net force of:',
    options: ['0 N', '1 N', '10 N', 'Cannot be determined'],
    answer: '0 N',
    difficulty: 'medium',
    hint: 'Constant velocity means zero acceleration. Apply F = ma.',
  },
  {
    id: 'sci-q6',
    subject: 'science',
    moduleId: 'chemistry-basics',
    questionNumber: 6,
    question: 'What is the chemical symbol for Sodium?',
    options: ['So', 'Na', 'Sd', 'S'],
    answer: 'Na',
    difficulty: 'easy',
    hint: 'It comes from the Latin name "Natrium".',
  },
  {
    id: 'sci-q7',
    subject: 'science',
    moduleId: 'chemistry-basics',
    questionNumber: 7,
    question: 'How many protons does Carbon have?',
    options: ['4', '6', '8', '12'],
    answer: '6',
    difficulty: 'easy',
    hint: 'The atomic number of Carbon is 6.',
  },
  {
    id: 'sci-q8',
    subject: 'science',
    moduleId: 'chemistry-basics',
    questionNumber: 8,
    question: 'Which type of bond involves the transfer of electrons?',
    options: ['Covalent', 'Ionic', 'Metallic', 'Hydrogen'],
    answer: 'Ionic',
    difficulty: 'medium',
    hint: 'This type of bond typically forms between metals and non-metals.',
  },
  {
    id: 'sci-q9',
    subject: 'science',
    moduleId: 'electricity-circuits',
    questionNumber: 9,
    question: 'What is the unit of electrical resistance?',
    options: ['Volts', 'Amperes', 'Ohms', 'Watts'],
    answer: 'Ohms',
    difficulty: 'easy',
    hint: 'Named after Georg Simon Ohm, symbolized by Ω.',
  },
  {
    id: 'sci-q10',
    subject: 'science',
    moduleId: 'electricity-circuits',
    questionNumber: 10,
    question: 'Using Ohm\'s Law, if V = 12V and R = 3Ω, what is the current?',
    options: ['2 A', '4 A', '6 A', '36 A'],
    answer: '4 A',
    difficulty: 'medium',
    hint: 'I = V/R = 12/3.',
  },
  {
    id: 'sci-q11',
    subject: 'science',
    moduleId: 'electricity-circuits',
    questionNumber: 11,
    question: 'Two 10Ω resistors in parallel have a combined resistance of:',
    options: ['20Ω', '10Ω', '5Ω', '2Ω'],
    answer: '5Ω',
    difficulty: 'hard',
    hint: '1/R_total = 1/R₁ + 1/R₂ = 1/10 + 1/10 = 2/10.',
  },
  {
    id: 'sci-q12',
    subject: 'science',
    moduleId: 'newtons-laws',
    questionNumber: 12,
    question: 'Why do passengers lurch forward when a bus suddenly stops?',
    options: ['Due to gravity', 'Due to inertia', 'Due to friction', 'Due to air resistance'],
    answer: 'Due to inertia',
    difficulty: 'easy',
    hint: 'Their body tends to continue moving even though the bus has stopped.',
  },
  {
    id: 'sci-q13',
    subject: 'science',
    moduleId: 'newtons-laws',
    questionNumber: 13,
    question: 'A force of 10 N acts on a 2 kg mass. What is the acceleration?',
    options: ['2 m/s²', '5 m/s²', '10 m/s²', '20 m/s²'],
    answer: '5 m/s²',
    difficulty: 'easy',
    hint: 'Apply F = ma → a = 10/2.',
  },
  {
    id: 'sci-q14',
    subject: 'science',
    moduleId: 'newtons-laws',
    questionNumber: 14,
    question: 'Which law explains why you need to wear seatbelts in a car?',
    options: ['First Law', 'Second Law', 'Third Law', 'Gravity'],
    answer: 'First Law',
    difficulty: 'easy',
    hint: 'Your body wants to keep moving forward when the car stops (Inertia).',
  },
  {
    id: 'sci-q15',
    subject: 'science',
    moduleId: 'newtons-laws',
    questionNumber: 15,
    question: 'If you push a wall with 100 N force, how much force does the wall push back with?',
    options: ['0 N', '50 N', '100 N', '200 N'],
    answer: '100 N',
    difficulty: 'easy',
    hint: "Newton's Third Law: Action and Reaction are equal.",
  },
  {
    id: 'sci-q16',
    subject: 'science',
    moduleId: 'newtons-laws',
    questionNumber: 16,
    question: 'Friction is a force that ____ motion between two surfaces.',
    options: ['increases', 'opposes', 'creates', 'helps'],
    answer: 'opposes',
    difficulty: 'easy',
    hint: 'Friction always acts in the direction opposite to motion.',
  },
  {
    id: 'sci-q17',
    subject: 'science',
    moduleId: 'newtons-laws',
    questionNumber: 17,
    question: "Mass is a measure of an object's ____.",
    options: ['Weight', 'Volume', 'Inertia', 'Speed'],
    answer: 'Inertia',
    difficulty: 'medium',
    hint: 'More mass means more resistance to change in motion.',
  },
  {
    id: 'sci-q18',
    subject: 'science',
    moduleId: 'newtons-laws',
    questionNumber: 18,
    question: 'Acceleration is defined as the rate of change of ____.',
    options: ['Distance', 'Velocity', 'Mass', 'Force'],
    answer: 'Velocity',
    difficulty: 'easy',
    hint: 'It measures how quickly speed or direction changes.',
  },
  {
    id: 'sci-q19',
    subject: 'science',
    moduleId: 'newtons-laws',
    questionNumber: 19,
    question: 'Weight is the force of ____ acting on an object.',
    options: ['Friction', 'Inertia', 'Gravity', 'Magnetism'],
    answer: 'Gravity',
    difficulty: 'easy',
    hint: 'W = mg, where g is acceleration due to gravity.',
  },
  {
    id: 'sci-q20',
    subject: 'science',
    moduleId: 'chemistry-basics',
    questionNumber: 20,
    question: 'What is the boiling point of water in Celsius at sea level?',
    options: ['0°C', '50°C', '100°C', '212°C'],
    answer: '100°C',
    difficulty: 'easy',
    hint: 'Water turns from liquid to gas at this temperature.',
  },

  // ═══════════════════════════════════════════
  //  PROGRAMMING — 20 Questions
  // ═══════════════════════════════════════════
  {
    id: 'prog-q1',
    subject: 'programming',
    moduleId: 'python-intro',
    questionNumber: 1,
    question: 'What does  print("Hello")  output?',
    options: ['Hello', '"Hello"', 'print(Hello)', 'Error'],
    answer: 'Hello',
    difficulty: 'easy',
    hint: 'print() displays its argument without the surrounding quotes.',
  },
  {
    id: 'prog-q2',
    subject: 'programming',
    moduleId: 'python-intro',
    questionNumber: 2,
    question: 'Which of these is a valid Python variable name?',
    options: ['2name', 'my-var', 'my_var', 'class'],
    answer: 'my_var',
    difficulty: 'easy',
    hint: "Variable names can't start with a number, can't use hyphens, and can't be reserved keywords.",
  },
  {
    id: 'prog-q3',
    subject: 'programming',
    moduleId: 'python-intro',
    questionNumber: 3,
    question: 'What is the data type of the value  3.14 ?',
    options: ['int', 'float', 'str', 'bool'],
    answer: 'float',
    difficulty: 'easy',
    hint: 'Decimal numbers in Python are called floating-point numbers.',
  },
  {
    id: 'prog-q4',
    subject: 'programming',
    moduleId: 'python-intro',
    questionNumber: 4,
    question: 'What is the output of:  print(10 // 3) ?',
    options: ['3', '3.33', '3.0', '4'],
    answer: '3',
    difficulty: 'medium',
    hint: '// is integer (floor) division — it drops the decimal part.',
  },
  {
    id: 'prog-q5',
    subject: 'programming',
    moduleId: 'python-intro',
    questionNumber: 5,
    question: 'What does  len("Python")  return?',
    options: ['5', '6', '7', 'Error'],
    answer: '6',
    difficulty: 'easy',
    hint: 'Count each character: P-y-t-h-o-n.',
  },
  {
    id: 'prog-q6',
    subject: 'programming',
    moduleId: 'javascript-intro',
    questionNumber: 6,
    question: 'Which keyword declares a constant variable in JavaScript?',
    options: ['var', 'let', 'const', 'static'],
    answer: 'const',
    difficulty: 'easy',
    hint: 'This keyword prevents reassignment of the variable.',
  },
  {
    id: 'prog-q7',
    subject: 'programming',
    moduleId: 'javascript-intro',
    questionNumber: 7,
    question: 'What is the output of:  typeof null  in JavaScript?',
    options: ['"null"', '"undefined"', '"object"', '"boolean"'],
    answer: '"object"',
    difficulty: 'hard',
    hint: 'This is a famous JavaScript quirk/bug that has existed since the first version.',
  },
  {
    id: 'prog-q8',
    subject: 'programming',
    moduleId: 'javascript-intro',
    questionNumber: 8,
    question: 'What does  document.querySelector("h1")  do?',
    options: ['Creates an h1 element', 'Selects the first h1 element', 'Deletes the h1 element', 'Styles the h1 element'],
    answer: 'Selects the first h1 element',
    difficulty: 'medium',
    hint: 'querySelector returns the first element matching the CSS selector.',
  },
  {
    id: 'prog-q9',
    subject: 'programming',
    moduleId: 'data-structures',
    questionNumber: 9,
    question: 'Which data structure uses LIFO (Last-In-First-Out)?',
    options: ['Queue', 'Stack', 'Array', 'Linked List'],
    answer: 'Stack',
    difficulty: 'easy',
    hint: 'Think of a stack of plates — you remove from the top.',
  },
  {
    id: 'prog-q10',
    subject: 'programming',
    moduleId: 'data-structures',
    questionNumber: 10,
    question: 'What is the time complexity of accessing an element by index in an array?',
    options: ['O(1)', 'O(n)', 'O(log n)', 'O(n²)'],
    answer: 'O(1)',
    difficulty: 'medium',
    hint: 'Arrays store elements in contiguous memory, so any index is directly calculable.',
  },
  {
    id: 'prog-q11',
    subject: 'programming',
    moduleId: 'data-structures',
    questionNumber: 11,
    question: 'Which data structure is best for a print job scheduler?',
    options: ['Stack', 'Queue', 'Binary Tree', 'Hash Map'],
    answer: 'Queue',
    difficulty: 'medium',
    hint: 'Print jobs should be processed in the order they were submitted (FIFO).',
  },
  {
    id: 'prog-q12',
    subject: 'programming',
    moduleId: 'python-intro',
    questionNumber: 12,
    question: 'What is the output of: x = [1,2,3]; x.append(4); print(len(x))',
    options: ['3', '4', '5', 'Error'],
    answer: '4',
    difficulty: 'medium',
    hint: 'append() adds one element to the list, so 3 + 1 = 4.',
  },
  {
    id: 'prog-q13',
    subject: 'programming',
    moduleId: 'python-intro',
    questionNumber: 13,
    question: 'How do you start a single-line comment in Python?',
    options: ['//', '/*', '#', '--'],
    answer: '#',
    difficulty: 'easy',
    hint: 'Python uses the hash character for comments.',
  },
  {
    id: 'prog-q14',
    subject: 'programming',
    moduleId: 'python-intro',
    questionNumber: 14,
    question: 'What is the result of  2 ** 3  in Python?',
    options: ['6', '8', '9', '5'],
    answer: '8',
    difficulty: 'easy',
    hint: '** is the exponentiation operator (2 raised to the power of 3).',
  },
  {
    id: 'prog-q15',
    subject: 'programming',
    moduleId: 'python-intro',
    questionNumber: 15,
    question: 'Which function is used to get input from the user in Python?',
    options: ['get()', 'scan()', 'input()', 'read()'],
    answer: 'input()',
    difficulty: 'easy',
    hint: 'It reads a line from input and returns it as a string.',
  },
  {
    id: 'prog-q16',
    subject: 'programming',
    moduleId: 'python-intro',
    questionNumber: 16,
    question: "How do you check if 'a' is equal to 'b' in Python?",
    options: ['a = b', 'a == b', 'a === b', 'a is b'],
    answer: 'a == b',
    difficulty: 'easy',
    hint: 'Double equals is the equality comparison operator.',
  },
  {
    id: 'prog-q17',
    subject: 'programming',
    moduleId: 'python-intro',
    questionNumber: 17,
    question: "What does the 'break' statement do in a Python loop?",
    options: ['Skips the current iteration', 'Exits the loop entirely', 'Restarts the loop', 'Pauses the loop'],
    answer: 'Exits the loop entirely',
    difficulty: 'medium',
    hint: 'It terminates the loop and moves to the next statement after the loop.',
  },
  {
    id: 'prog-q18',
    subject: 'programming',
    moduleId: 'python-intro',
    questionNumber: 18,
    question: 'Which data type is used for a collection of unique elements in Python?',
    options: ['list', 'tuple', 'set', 'dict'],
    answer: 'set',
    difficulty: 'medium',
    hint: 'Sets do not allow duplicate values.',
  },
  {
    id: 'prog-q19',
    subject: 'programming',
    moduleId: 'python-intro',
    questionNumber: 19,
    question: 'What is the output of  print("Python"[0]) ?',
    options: ['P', 'y', 'n', 'Error'],
    answer: 'P',
    difficulty: 'easy',
    hint: 'Python uses zero-based indexing for strings.',
  },
  {
    id: 'prog-q20',
    subject: 'programming',
    moduleId: 'python-intro',
    questionNumber: 20,
    question: 'Which keyword is used for an "otherwise" condition in Python?',
    options: ['otherwise', 'elif', 'else', 'except'],
    answer: 'else',
    difficulty: 'easy',
    hint: "It catches everything that doesn't match the if or elif conditions.",
  },
]

// Helper: get questions by subject
export function getQuestionsBySubject(subject: string): PracticeQuestion[] {
  return PRACTICE_QUESTIONS.filter((q) => q.subject === subject)
}

// Helper: get all subjects with question counts
export function getSubjectStats() {
  const subjects = ['math', 'science', 'programming'] as const
  return subjects.map((s) => ({
    subject: s,
    count: PRACTICE_QUESTIONS.filter((q) => q.subject === s).length,
  }))
}
